import Foundation

/// Pure renderers for `CrapReport`. Lives in core so the CLI's `analyze` command
/// stays a thin shim — and so the formatters can be unit-tested without piping
/// real stdout. Two outputs: a human-readable text block and canonical JSON.
public enum CrapReportFormatter: Sendable {

    /// Pretty text rendering — leading metadata, a summary table, then the top-N
    /// methods by wCRAP descending. Methods above threshold are marked with `!`
    /// so the table works as a "where to go next" guide even when no method is
    /// strictly crappy.
    public static func pretty(_ report: CrapReport, topN: Int = 20) -> String {
        var out = ""
        out += header(report)
        out += "\n"
        if !report.notes.isEmpty {
            out += notes(report)
            out += "\n"
        }
        out += summary(report)
        out += "\n"
        out += topMethodsByCrap(report, topN: topN)
        return out
    }

    /// Canonical JSON encoding — sorted keys, ISO-8601 dates, slash unescape off
    /// to keep the output diff-friendly in CI.
    public static func json(_ report: CrapReport, prettyPrinted: Bool = true) throws -> Data {
        let encoder = JSONEncoder()
        encoder.outputFormatting = prettyPrinted
            ? [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
            : [.sortedKeys, .withoutEscapingSlashes]
        encoder.dateEncodingStrategy = .iso8601
        return try encoder.encode(report)
    }

    /// Render an error envelope as JSON or as a single-line CLI message.
    public static func errorText(_ envelope: SlopguardErrorEnvelope) -> String {
        "slopguard-swift: [\(envelope.code)] \(envelope.message)"
    }

    public static func errorJSON(_ envelope: SlopguardErrorEnvelope) throws -> Data {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        return try encoder.encode(["error": envelope])
    }

    // MARK: - Text helpers

    private static func header(_ report: CrapReport) -> String {
        let xcresultLine: String
        if let path = report.xcresultPath {
            xcresultLine = path
        } else if report.coverageAvailable {
            xcresultLine = "(generated by xcodebuild — bundle cleaned up after run)"
        } else {
            xcresultLine = "(none — coverage assumed 0%)"
        }
        return """
        slopguard-swift \(report.toolVersion) — schema \(report.schemaVersion)
        source:    \(report.sourceRoot)
        xcresult:  \(xcresultLine)
        threshold: \(formatNumber(report.threshold))

        """
    }

    private static func notes(_ report: CrapReport) -> String {
        var out = "Notes\n"
        for note in report.notes {
            out += "  • \(note)\n"
        }
        return out
    }

    private static func summary(_ report: CrapReport) -> String {
        let s = report.summary
        var out = "Summary\n"
        out += String(format: "  files:     %d\n", s.fileCount)
        out += String(format: "  types:     %d  (crappy: %d)\n", s.typeCount, s.crappyTypeCount)
        out += String(format: "  methods:   %d  (crappy: %d)\n", s.methodCount, s.crappyMethodCount)
        out += String(format: "  avg crap:  %.2f\n", s.averageCrap)
        out += String(format: "  max crap:  %.2f\n", s.maxCrap)
        out += String(format: "  avg cyc:   %.2f\n", s.averageComplexity)
        out += String(format: "  avg cog:   %.2f\n", s.averageCognitiveComplexity)
        out += String(format: "  avg wt:    %.2f\n", s.averageWeightedComplexity)
        if let weighted = s.weightedCoverage {
            out += String(format: "  coverage:  %.1f%%\n", weighted)
        } else {
            out += "  coverage:  unavailable (run without --no-coverage to gather it)\n"
        }
        return out
    }

    private static func topMethodsByCrap(_ report: CrapReport, topN: Int) -> String {
        let ranked = report.methods.sorted { $0.crap > $1.crap }.prefix(topN)
        if ranked.isEmpty {
            return "No methods analyzed.\n"
        }
        let crappyTotal = report.summary.crappyMethodCount
        let header: String
        if crappyTotal > 0 {
            header = "Top methods by wCRAP (\(crappyTotal) above threshold \(formatNumber(report.threshold)), marked !)"
        } else {
            header = "Top methods by wCRAP (none above threshold \(formatNumber(report.threshold)) — ranked hotspots to watch)"
        }
        var out = "\(header)\n"
        for m in ranked {
            // cyc=cyclomatic, cog=cognitive, wt=weighted. Skew between cyc and
            // cog tells the agent whether a high CRAP is real (both high) or
            // a flat-dispatch artefact (cyc high, cog low → wt small → CRAP
            // is honest).
            let marker = m.isCrappy ? "!" : " "
            out += String(
                format: "%@ %7.2f  cyc=%-3d cog=%-3d wt=%5.2f cov=%5.1f%%  %@:%d  %@\n",
                marker, m.crap, m.complexity, m.cognitiveComplexity, m.weightedComplexity,
                m.coverage, m.file, m.line, m.qualifiedName
            )
        }
        return out
    }

    private static func formatNumber(_ d: Double) -> String { String(format: "%.1f", d) }
}
