import Foundation
import MCP
import SlopguardCore
import SlopguardCoverage

enum AnalyzeDirectoryTool {

    static let definition = ToolDefinition(
        name: "analyze_directory",
        title: "Analyze a directory",
        description: """
            Walk a directory of Swift sources, compute cyclomatic complexity for every \
            function/initializer/subscript/accessor, drive `xcodebuild test` to gather \
            line coverage, and return a full CrapReport (methods + types + summary). \
            Coverage is generated by slopguard-swift itself — callers don't supply it. The \
            report is cached server-side so subsequent calls to get_crap_report, \
            find_crappy_code, and get_coverage_gaps return without re-analyzing.
            """,
        inputSchema: ToolSchemas.analyzeDirectory,
        handler: { args, pipeline, cache in
            guard let path = ToolUtilities.string(args, "path") else {
                return ToolUtilities.errorResult(.init(.invalidArgument(name: "path", reason: "required string argument")))
            }
            let url = ToolUtilities.resolvePath(path)
            let threshold = ToolUtilities.double(args, "threshold") ?? CRAP.defaultThreshold
            let include = ToolUtilities.stringArray(args, "include") ?? []
            let extraExclude = ToolUtilities.stringArray(args, "exclude") ?? []
            let noDefaults = ToolUtilities.bool(args, "noDefaultExcludes") ?? false
            let baseExclude = noDefaults ? [] : AnalysisOptions.defaultExcludeGlobs
            let options = AnalysisOptions(
                includeGlobs: include,
                excludeGlobs: baseExclude + extraExclude
            )
            let coverage = ToolUtilities.autoCoverage(args)

            do {
                let report = try await pipeline.run(
                    sourceURL: url,
                    coverage: coverage,
                    threshold: threshold,
                    options: options
                )
                await cache.store(
                    report: report,
                    sourceRoot: url.standardizedFileURL.path,
                    xcresultPath: report.xcresultPath
                )
                return try ToolUtilities.successResult(report)
            } catch let error as SlopguardError {
                return ToolUtilities.errorResult(.init(error))
            } catch {
                return ToolUtilities.errorResult(.init(code: "internal_error", message: "\(error)"))
            }
        }
    )
}
